const mongoose = require("mongoose");
const registrationSchema = new mongoose.Schema({
    sName:{
        type:String,
        required:true,
    },
    fName:{
        type:String,
        required:true,
    },
    mName:{
        type:String,
        required:true,
    },
    email:{
        type:String,
        required:true,
        unique:true,
    },
    dob:{
        type:String,
        required:true,
    },
    mobile:{
        type:Number,
        required:true,
        unique:true,
    },
    aadhar:{
        type:String,
    },
    gender:{
        type:String,
        enum:["male","female"],
    },
    address:{
        type:String,
        required:true,
    },
    religion:{
        type:String,
    },
    state:{
        type:String,
    },
    courses:{
        type:String,
        enum:["BCA","B.A","B.SC","B.COM"],
    },
    image:{
        type:String,
        set: (v)=> v === "" ?"https://images.unsplash.com/photo-1701203580497-e49d73574908?q=80&w=1935&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D":v,
    },
    hobby:{
        type:Array,
    },
    boardName:{
        type:String,
    },
    boardPercentage:{
        type:Number,
    },
    boardYear:{
        type:Number,
    },
    intermediateName:{
        type:String,
    },
    intermediatePercentage:{
        type:Number,
    },
    intermediateYear:{
        type:Number,
    },
    graduationName:{
        type:String,
    },
    graduationPercentage:{
        type:Number,
    },
    graduationYear:{
        type:Number,
    },
    masterName:{
        type:String,
    },
    masterPercentage:{
        type:Number,
    },
    masterYear:{
        type:Number,
    },
    applyDate:{
        type:String,
    },
    _id:{
        type:String,
    },
});
const Registration = mongoose.model("Registration",registrationSchema);

module.exports= Registration;

